# Generated by Django 4.1.3 on 2023-03-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_ans_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='que/images'),
        ),
    ]
