# Generated by Django 4.1.3 on 2023-03-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_que_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='que/images'),
        ),
        migrations.AddField(
            model_name='que',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='que/images'),
        ),
        migrations.AddField(
            model_name='que',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='que/images'),
        ),
        migrations.AddField(
            model_name='que',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='que/images'),
        ),
    ]
