# Generated by Django 4.1.3 on 2023-03-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_que_image_a_que_image_b_que_image_c_que_image_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='expiry_date',
        ),
    ]
