# Generated by Django 4.1.3 on 2023-03-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_contact_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
