# Generated by Django 4.1.3 on 2023-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Media/que'),
        ),
        migrations.AlterField(
            model_name='que',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='Media/ans'),
        ),
        migrations.AlterField(
            model_name='que',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='Media/ans'),
        ),
        migrations.AlterField(
            model_name='que',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='Media/ans'),
        ),
        migrations.AlterField(
            model_name='que',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='media/ans'),
        ),
    ]
